### ISSUE TITLE
Option to use profiles?

### ISSUE THREAD

**Issue by jtwp** [kromtech/s3-inspector#4]
Is there any option to use profiles, so we can assume a role from another account, or can it only call default credentials?

**Comment by ze0adik** [comment]
Thank you for your interest in our tool. We are planning to add profile selection support soon, meanwhile you can check solution contributed in https://github.com/kromtech/s3-inspector/pull/2

**Comment by Volfar** [comment]
Hi, @jtwp 
We just added support for AWS profiles in cb9abafcc9eadd86bca3d5b8b030f6c3479e11db.
The original solution was contributed in 40177c4ad35ae86c7ad39a46ce9e194d8375a1ca by @vpistis .
Check it out!
